# Python - Operações com Matrizes

## 1. Operações com matrizes
* Observe com é simples fazer operações com matrizes
* Operação de Dividir os elementos de uma matriz por outra é simplesmente m2 / m1
* Operação de Arredondamento dos elementos de uma matriz
* Operação de Multiplicação dos elementos de uma matriz
* Operação de Soma dos elementos de uma matriz
* Operação de Subtraão dos elementos de uma matriz
* Operação de Exponenciação dos elementos de uma matriz

In [11]:
import numpy as np
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[7,8,9],[10,11,12]])
print('m1:\n', m1)
print('m2:\n', m2)
print('m2/m1:\n', m2/m1) # para cada elemento (i,j) de m2 aplicar a divisão pelo elemento (i,j) de m1
print('np.matrix.round(m2/m1):\n', np.matrix.round(m2/m1)) # arredondando cada um dos elementos
print('10 * m2:\n', 10 * m2)
print('m1 + 5:\n', m1 + 5)
print('m2 - 1:\n', m2 - 1)
print('m1 ** 2:\n', m1 ** 2)


m1:
 [[1 2 3]
 [4 5 6]]
m2:
 [[ 7  8  9]
 [10 11 12]]
m2/m1:
 [[7.  4.  3. ]
 [2.5 2.2 2. ]]
np.matrix.round(m2/m1):
 [[7. 4. 3.]
 [2. 2. 2.]]
10 * m2:
 [[ 70  80  90]
 [100 110 120]]
m1 + 5:
 [[ 6  7  8]
 [ 9 10 11]]
m2 - 1:
 [[ 6  7  8]
 [ 9 10 11]]
m1 ** 2:
 [[ 1  4  9]
 [16 25 36]]
